name: flutter_app_transmuter
description: Transmute your Flutter application using one command from terminal.  Facilitates many types of
  application changes such as rebranding, changing package and bundle ids, changing API keys in
  AndroidManifest.xml or AppDelegate.swift, swapping resources and icons,
  swapping out source files, etc.
version: 2.1.0
maintainer: Tim Maffett
homepage: https://github.com/timmaffett/flutter_app_transmuter
repository: https://github.com/timmaffett/flutter_app_transmuter
issue_tracker: https://github.com/timmaffett/flutter_app_transmuter/issues

# variations on the transmuter name - depending on how the user wants to invoke the command
executables:
  transmute: main
  transmuter: main
  app_transmuter: main
  flutter_app_transmuter: main

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.2
  chalkdart: ^3.0.5
  glob: ^2.1.2
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  test: ^1.24.0


